# Generated by Django 2.2.4 on 2019-10-31 11:21

from django.db import migrations, models
import publication.models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20191031_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='content_audio',
            field=models.FileField(null=True, upload_to=publication.models.Publication.publication_directory_path),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_img',
            field=models.FileField(null=True, upload_to=publication.models.Publication.publication_directory_path),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_video',
            field=models.FileField(null=True, upload_to=publication.models.Publication.publication_directory_path),
        ),
    ]
