# Generated by Django 2.2.4 on 2019-10-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20191031_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content_video',
            field=models.CharField(max_length=255, null=True, verbose_name='Contenu video'),
        ),
    ]
