# Generated by Django 2.2.4 on 2019-10-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20191031_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='content_audio',
        ),
    ]
