# Generated by Django 2.2.4 on 2019-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_remove_publication_content_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='add_to_slider',
            field=models.BooleanField(default=False, help_text='Add this publication to slider ', verbose_name='Add to slider ?'),
        ),
    ]
