# Generated by Django 2.2.4 on 2019-11-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_publication_add_to_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='content',
            new_name='question',
        ),
    ]
