# Generated by Django 2.2.4 on 2019-11-07 22:45

from django.db import migrations, models
import django.db.models.deletion
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_auto_20191105_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answers',
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(default=models.CharField(default=utils.refs.reference, max_length=255, unique=True), max_length=255, unique=True, verbose_name='Bonne reponse'),
        ),
        migrations.AddField(
            model_name='questions',
            name='wrong_answer1',
            field=models.CharField(default=models.CharField(default=utils.refs.reference, max_length=255, unique=True), max_length=255, unique=True, verbose_name='Première fausse reponse'),
        ),
        migrations.AddField(
            model_name='questions',
            name='wrong_answer2',
            field=models.CharField(default=models.CharField(default=utils.refs.reference, max_length=255, unique=True), max_length=255, unique=True, verbose_name='Deuxième fausse reponse'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quizz',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='publication.Quizz'),
        ),
    ]
