# Generated by Django 2.2.4 on 2019-11-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0011_auto_20191107_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'La publication', 'verbose_name_plural': 'Les publications'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Question quizz', 'verbose_name_plural': 'Questions quizz'},
        ),
        migrations.AlterModelOptions(
            name='quizz',
            options={'verbose_name': 'Le quizz', 'verbose_name_plural': 'Les Quizz'},
        ),
    ]
