# Generated by Django 2.2.4 on 2019-11-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_auto_20191108_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
    ]
