# Generated by Django 2.2.4 on 2019-11-10 12:24

from django.db import migrations, models
import django.db.models.deletion
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Event type's status in the system", verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Catégorie de publication',
                'verbose_name_plural': 'Catégories de publication',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(help_text="Type d'evènement", max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.EventType'),
        ),
    ]
