# Generated by Django 2.2.4 on 2019-11-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_geo_manager'),
        ('event', '0003_auto_20191110_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': "Type d'évènement", 'verbose_name_plural': "Type d'évènements"},
        ),
        migrations.AddField(
            model_name='event',
            name='geo_zone',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Geo'),
        ),
    ]
