# Generated by Django 2.2.4 on 2019-11-12 21:56

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191112_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='illustration',
            field=models.FileField(null=True, upload_to=event.models.Event.event_directory_path),
        ),
    ]
