# Generated by Django 2.2.4 on 2019-10-29 09:04

from django.db import migrations, models
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20191029_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='code',
            field=models.CharField(default=utils.refs.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
