# Generated by Django 2.2.4 on 2019-11-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20191110_1232'),
        ('base', '0009_auto_20191108_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geo',
        ),
    ]
