# Generated by Django 2.2.4 on 2020-01-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20191118_1106'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='geo_zone',
            field=models.ManyToManyField(blank=True, max_length=128, null=True, to='geo.Geo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('AGREED', 'AGREED'), ('VISITOR', 'VISITOR'), ('EDITOR', 'EDITOR')], default='SIMPLE', max_length=255),
        ),
    ]
