# Generated by Django 2.2.4 on 2020-01-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20191118_1106'),
        ('users', '0002_auto_20200108_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='geo_zone',
        ),
        migrations.AddField(
            model_name='profile',
            name='geo_zone',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Geo'),
        ),
    ]
