# Generated by Django 2.2.4 on 2019-10-18 17:14

from django.db import migrations, models
import django.db.models.deletion
import project.models
import utils.refs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=1000)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investor', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
                ('investment_type', models.CharField(max_length=255)),
                ('illustration', models.FileField(upload_to=project.models.Project.project_directory_path)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Starting date')),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Quizz's status in the system", verbose_name='Status')),
                ('geo_zone', models.ManyToManyField(blank=True, max_length=128, null=True, to='base.Geo')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=255)),
                ('content_text', models.CharField(max_length=255)),
                ('content_img', models.CharField(max_length=255)),
                ('content_video', models.CharField(max_length=255)),
                ('content_audio', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Comment's status in the system", verbose_name='Status')),
                ('profile', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
                ('project', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
