# Generated by Django 2.2.4 on 2019-10-23 10:05

from django.db import migrations, models
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191019_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Event's status in the system", verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
