# Generated by Django 2.2.4 on 2019-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
    ]
