# Generated by Django 2.2.4 on 2019-10-29 16:21

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content_audio',
            field=models.FileField(null=True, upload_to=project.models.Comments.comment_directory_path),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_img',
            field=models.FileField(null=True, upload_to=project.models.Comments.comment_directory_path),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_video',
            field=models.FileField(null=True, upload_to=project.models.Comments.comment_directory_path),
        ),
    ]
