# Generated by Django 2.2.4 on 2019-10-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191029_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='evolution',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
