# Generated by Django 2.2.4 on 2019-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20191030_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=10000000000),
        ),
    ]
