# Generated by Django 2.2.4 on 2019-11-03 15:16

from django.db import migrations, models
import django.db.models.deletion
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_late_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractedEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
            ],
            options={
                'verbose_name': 'Contracted entreprise',
                'verbose_name_plural': 'Contracted entreprises',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='contracted_entreprise',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.ContractedEntreprise'),
        ),
    ]
