# Generated by Django 2.2.4 on 2019-11-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20191104_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='contractedentreprise',
            options={'verbose_name': 'Prestataires', 'verbose_name_plural': 'Prestataires'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evènement', 'verbose_name_plural': 'Evènements'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='geo_zone',
        ),
    ]
