# Generated by Django 2.2.4 on 2019-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('project', '0014_auto_20191110_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geo_zone',
            field=models.ManyToManyField(blank=True, max_length=128, null=True, to='geo.Geo'),
        ),
    ]
