# Generated by Django 2.2.4 on 2019-11-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_project_geo_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='investment_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
