# Generated by Django 2.2.4 on 2019-11-10 11:53

from django.db import migrations, models
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20191110_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Funding's type  status in the system", verbose_name='Status')),
            ],
            options={
                'verbose_name': "Type d'investissement",
                'verbose_name_plural': "Types d'investissements",
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Project's type  status in the system", verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Type de projet',
                'verbose_name_plural': 'Types de projets',
            },
        ),
    ]
