# Generated by Django 2.2.4 on 2019-11-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_fundingtype_projecttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
