# Generated by Django 2.2.4 on 2019-11-10 12:58

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20191110_1357'),
        ('project', '0018_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True, help_text='Statut', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Denonciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=255)),
                ('content_text', models.CharField(max_length=255)),
                ('content_img', models.FileField(null=True, upload_to=project.models.Denonciation.tracka_directory_path)),
                ('content_video', models.FileField(null=True, upload_to=project.models.Denonciation.tracka_directory_path)),
                ('content_audio', models.FileField(null=True, upload_to=project.models.Denonciation.tracka_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=False, help_text='Information vérifiée', verbose_name='Information vérifiée')),
                ('geo_zone', models.ManyToManyField(blank=True, max_length=128, null=True, to='geo.Geo')),
                ('project', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project')),
            ],
            options={
                'verbose_name': 'Denonciation / Tracka',
                'verbose_name_plural': 'Denonciations / Trackas',
            },
        ),
    ]
