# Generated by Django 2.2.4 on 2019-11-18 10:22

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20191118_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content_audio',
            field=models.FileField(blank=True, null=True, upload_to=project.models.Comments.comment_directory_path),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_img',
            field=models.FileField(blank=True, null=True, upload_to=project.models.Comments.comment_directory_path),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_video',
            field=models.FileField(blank=True, null=True, upload_to=project.models.Comments.comment_directory_path),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='content_audio',
            field=models.FileField(blank=True, null=True, upload_to=project.models.Denonciation.tracka_directory_path),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='content_img',
            field=models.FileField(blank=True, null=True, upload_to=project.models.Denonciation.tracka_directory_path),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='content_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='content_video',
            field=models.FileField(blank=True, null=True, upload_to=project.models.Denonciation.tracka_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='investor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
