# Generated by Django 2.2.4 on 2019-12-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20191118_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
