# Generated by Django 2.2.4 on 2020-01-03 16:22

from django.db import migrations, models
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20191230_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reference',
            field=models.CharField(default=utils.refs.reference, max_length=255, unique=True),
        ),
        
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
