# Generated by Django 2.2.4 on 2020-01-03 16:25

from django.db import migrations, models
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20200103_1722'),
    ]

    operations = [
        
    ]
