# Generated by Django 2.2.4 on 2020-01-03 16:27

from django.db import migrations, models
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20200103_1725'),
    ]

    operations = [
       
    ]
