# Generated by Django 2.2.4 on 2020-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20200103_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
