# Generated by Django 2.2.4 on 2020-01-23 12:14

from django.db import migrations, models
import django.db.models.deletion
import utils.refs
import vote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20200108_1525'),
        ('geo', '0010_auto_20191118_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text='Status in the system', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Scrutin',
                'verbose_name_plural': 'Scrutins',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text='status in the system', verbose_name='Status')),
            ],
            options={
                'verbose_name': "Type d'incident",
                'verbose_name_plural': "Types d'incident",
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=vote.models.Observer.observer_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Observer's status in the system", verbose_name='Status')),
                ('profile', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
            ],
            options={
                'verbose_name': 'Observateur',
                'verbose_name_plural': 'Observateurs',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('vote_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Starting date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Vote's status in the system", verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Scrutin',
                'verbose_name_plural': 'Scrutin',
            },
        ),
        migrations.CreateModel(
            name='VoteOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('open_hour', models.TimeField(blank=True, max_length=255, null=True)),
                ('close_hour', models.TimeField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="VoteOffice's status in the system", verbose_name='Status')),
                ('geo_zone', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Geo')),
            ],
            options={
                'verbose_name': 'Bureau de vote',
                'verbose_name_plural': 'Bureaux de vote',
            },
        ),
        migrations.CreateModel(
            name='VoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text='status in the system', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Scrutin',
                'verbose_name_plural': 'Scrutins',
            },
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('subscribed_number', models.BigIntegerField(blank=True, null=True)),
                ('voters_number', models.BigIntegerField(blank=True, null=True)),
                ('spoiled_ballots', models.BigIntegerField(blank=True, null=True, verbose_name='Bulletins nuls')),
                ('abstention', models.BigIntegerField(blank=True, null=True, verbose_name='Abstention')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Candidate's status in the system", verbose_name='Status')),
                ('observer', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.Observer')),
                ('vote', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.Vote')),
                ('vote_office', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.VoteOffice')),
            ],
            options={
                'verbose_name': 'Résultat de vote',
                'verbose_name_plural': 'Résultats de vote',
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.VoteType'),
        ),
        migrations.AddField(
            model_name='observer',
            name='vote_office',
            field=models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.VoteOffice'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('incident_hour', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('incident_type', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.IncidentType')),
                ('reported_by', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.Observer')),
                ('vote_office', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.VoteOffice')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=utils.refs.reference, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parti', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=vote.models.Candidate.candidate_directory_path)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Candidate's status in the system", verbose_name='Status')),
                ('type', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.CandidateType')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
    ]
