# Generated by Django 2.2.4 on 2019-11-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='geo_zone',
            new_name='questions',
        ),
    ]
