# Generated by Django 2.2.4 on 2019-11-10 11:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('COUNTRY', 'COUNTRY'), ('CERCLE', 'CERCLE'), ('REGION', 'REGION'), ('ARRONDISSEMENT', 'ARRONDISSEMENT'), ('COMMUNE', 'COMMUNE')], default='COUNTRY', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geo.Geo')),
            ],
            options={
                'verbose_name': 'Découpage administratif ',
                'verbose_name_plural': 'Découpages administratifs',
            },
        ),
    ]
