# Generated by Django 2.2.4 on 2019-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_pdecs'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='lat',
            field=models.CharField(max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='geo',
            name='lon',
            field=models.CharField(max_length=255, null=True, verbose_name='Longitude'),
        ),
    ]
