# Generated by Django 2.2.4 on 2019-11-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20191110_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdecsdetailedbudget',
            name='pdecs',
            field=models.ForeignKey(help_text='PDECS Budget', max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.PDECS'),
        ),
    ]
