# Generated by Django 2.2.4 on 2019-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20191110_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdecsdetailedbudget',
            name='actions',
            field=models.CharField(max_length=255, null=True, verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='pdecsdetailedbudget',
            name='objectifs',
            field=models.CharField(max_length=255, null=True, verbose_name='Objectifs'),
        ),
        migrations.AddField(
            model_name='pdecsdetailedbudget',
            name='sous_secteur',
            field=models.CharField(max_length=25, null=True, verbose_name='Sous secteur'),
        ),
        migrations.AddField(
            model_name='pdecsdetailedbudget',
            name='year',
            field=models.CharField(max_length=255, null=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='pdecsdetailedbudget',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Coût'),
        ),
    ]
