# Generated by Django 2.2.4 on 2019-11-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20191111_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdecsdetailedbudget',
            name='name',
        ),
    ]
