# Generated by Django 2.2.4 on 2019-11-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_remove_pdecsdetailedbudget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='area',
            field=models.CharField(max_length=255, null=True, verbose_name='Superficie'),
        ),
        migrations.AddField(
            model_name='geo',
            name='nb_hbts',
            field=models.CharField(max_length=255, null=True, verbose_name="Nombre d'habitants"),
        ),
    ]
