# Generated by Django 2.2.4 on 2019-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20191112_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='manager',
            field=models.CharField(max_length=255, null=True, verbose_name='Manager'),
        ),
    ]
