# Generated by Django 2.2.4 on 2019-11-18 10:06

from django.db import migrations, models
import utils.refs


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_geo_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Superficie'),
        ),
        migrations.AlterField(
            model_name='geo',
            name='code',
            field=models.CharField(default=utils.refs.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='geo',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='geo',
            name='nb_hbts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nombre d'habitants"),
        ),
        migrations.AlterField(
            model_name='pdecsdetailedbudget',
            name='budget',
            field=models.IntegerField(max_length=20, verbose_name='Coût'),
        ),
    ]
